services:
  api:
    container_name: talkie_api_staging
    build:
      context: .
      target: staging
      dockerfile: Dockerfile
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      - db
    image: talkie_api_staging
    networks:
      - talkie_net
    restart: always
    env_file:
      - .env.staging

  db:
    container_name: ${DB_HOST}
    image: postgres:14.3
    restart: always
    networks:
      - talkie_net
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}
    volumes:
      - ./postgres/staging:/var/lib/postgresql/data

networks:
  talkie_net:
